# Generated by Django 6.0 on 2026-06-15 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
        ('bd_models', '0015_alter_ballinstance_server_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Deck', max_length=32)),
                ('selected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battle_decks', to='bd_models.player')),
            ],
            options={
                'unique_together': {('player', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BattleDeckSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('active', 'Active'), ('bench', 'Bench')], max_length=16)),
                ('position', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ball_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_deck_slots', to='bd_models.ballinstance')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='battle.battledeck')),
            ],
            options={
                'unique_together': {('deck', 'ball_instance'), ('deck', 'slot_type', 'position')},
            },
        ),
    ]
